#! configuration/production.yaml
application:
  host: 0.0.0.0
  base_url: "http://0.0.0.0"
database:
  require_ssl: false
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "d.crearer@src-trace.com"